###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md

require 'dotenv'
Dotenv.load("../.env")

def get_env(name)
  value = ENV[name]
  raise "Forgot to define #{name} in enviornment" unless value 

  return value 
end 

env = {
  :developer_email => get_env("DEVELOPER_EMAIL"),
  :developer_first_name => get_env("DEVELOPER_FIRST_NAME"),
  :developer_last_name => get_env("DEVELOPER_LAST_NAME"),
  :developer_phone_number => get_env("DEVELOPER_PHONE_NUMBER"),
  :app_name => get_env("APP_NAME"),
  :app_id => get_env("APPLE_APP_ID")
}

company_name = "Company name"

name({
  'en-US' => env[:app_name]
})
subtitle({
  'en-US' => "Description added under app name. Max of 30 characters."
})
description({
  'en-US' => "description for app store here."
})
keywords({
  'en-US' => "word,word2,word3"
})
promotional_text({
  'en-US' => "Short, 170 character limit text that shows above app description. The promotional text may include product’s news, the oncoming new features and contents, promotional activities or other details about app."
})
support_url({
  'en-US' => "https://you.com/contact/index.html`"
})
marketing_url({
  'en-US' => "https://you.com/features/index.html"
})
privacy_url({
  'en-US' => "https://you.com/privacy/index.html"
})

# See: https://docs.fastlane.tools/actions/deliver/#available-categories for options
primary_category "MZGenre.Games"
primary_first_sub_category "MZGenre.Sports"
secondary_category "MZGenre.Sports"

# See: https://github.com/artsy/eigen/blob/faa02e2746194d8d7c11899474de9c517435eca4/fastlane/Fastfile#L131-L149 for options
submission_information({
  add_id_info_serves_ads: false,
  add_id_info_uses_idfa: false, #If using admob, set to true
  add_id_info_tracks_install: false,
  add_id_info_tracks_action: false,
  content_rights_contains_third_party_content: false,
  export_compliance_contains_proprietary_cryptography: false,
  export_compliance_contains_third_party_cryptography: false,
  export_compliance_uses_encryption: true, # If using keychain, set to true
  export_compliance_is_exempt: true # If only using keychain, set to true
})

# Check out the fastlane/rating_config.json file and fill it out. 
# See: https://docs.fastlane.tools/actions/deliver/#available-age-rating-groups for options 

# -------------- Done editing variables ------------------

app env[:app_id]

languages(['en-US'])

# must be exactly 1024x1024px
app_icon "./fastlane/icons/icon.jpg"

release_notes({
  'en-US' => File.open(Dir.pwd + "/fastlane/release_notes.txt", "rb").read
})

screenshots_path "./fastlane/screenshots/"

force true # Skip the HTML report file verification
submit_for_review false 
automatic_release true
price_tier 0 # price 
overwrite_screenshots true

trade_representative_contact_information(
  first_name: "First",
  last_name: "Last",
  trade_name: company_name,
  address_line1: "123 Sesame St", # can add line2 and line3,
  city_name: "City",
  state: "Iowa",
  country: "United States",
  postal_code: "43221",
  phone_number: "+1 3333333333",
  email_address: "you@company.com",
  is_displayed_on_app_store: false
)

app_review_information(
  first_name: env[:developer_first_name],
  last_name: env[:developer_last_name],
  phone_number: env[:developer_phone_number],
  email_address: env[:developer_email],
  demo_user: "demo@you.com",
  demo_password: "password",
  notes: "Login with email and password at the login screen."
)

app_rating_config_path './fastlane/rating_config.json'

platform 'ios'

copyright "#{Time.now.year} #{company_name}"

